apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: yyz.ocir.io/yzukikevdw6w/mywebserver:v1
        name: webserver
      imagePullSecrets:
      - name: ocirsecret
